// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0CLfKW9mg5xKtPrlGAUmBp8QM9SOXFM0',
    appId: '1:1055951057562:web:0e6d85df8ce9f8371be523',
    messagingSenderId: '1055951057562',
    projectId: 'outreach-social',
    authDomain: 'outreach-social.firebaseapp.com',
    storageBucket: 'outreach-social.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE-matJ__y1GcwLeMURaPk56kE8DAlLqM',
    appId: '1:1055951057562:android:a3a7191f171421a61be523',
    messagingSenderId: '1055951057562',
    projectId: 'outreach-social',
    storageBucket: 'outreach-social.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLnXDJX8lVJeHV2e3zf4VTxyEnT-lQzjQ',
    appId: '1:1055951057562:ios:710ba3a1f79dc4711be523',
    messagingSenderId: '1055951057562',
    projectId: 'outreach-social',
    storageBucket: 'outreach-social.appspot.com',
    androidClientId: '1055951057562-24cu5g0cant70uei4mm6facicjnm8knc.apps.googleusercontent.com',
    iosClientId: '1055951057562-hlj22gch50uvuku1o5b8tsofkv0pbm64.apps.googleusercontent.com',
    iosBundleId: 'com.outreach.social',
  );

}