// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1D1jECBxwtJCng7KDmV_nV67gEa6Ty2Y',
    appId: '1:497882681132:web:19bd2f7293fec3ebd8e689',
    messagingSenderId: '497882681132',
    projectId: 'outreach-dev-62760',
    authDomain: 'outreach-dev-62760.firebaseapp.com',
    storageBucket: 'outreach-dev-62760.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwlF0TX0eIboUIfOSeWSc8AMcv9Kr9yt8',
    appId: '1:497882681132:android:db7c971b073466e1d8e689',
    messagingSenderId: '497882681132',
    projectId: 'outreach-dev-62760',
    storageBucket: 'outreach-dev-62760.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0tAt2QwflHo_RbOzaJBt4cqSoD-BHBzA',
    appId: '1:497882681132:ios:45482785abe1843cd8e689',
    messagingSenderId: '497882681132',
    projectId: 'outreach-dev-62760',
    storageBucket: 'outreach-dev-62760.firebasestorage.app',
    iosClientId: '497882681132-kdpucpjagq99osgo3r3fus8tcfguqlpl.apps.googleusercontent.com',
    iosBundleId: 'com.outreach.social',
  );

}