on:
  pull_request:
    branches:
    - dev
  push:
    branches:
    - dev

name: "Convert and Store Keystore"

jobs:
  convert-and-store:
    name: Convert and Store Keystore
    runs-on: ubuntu-latest
    steps:
    - name: Decode base64 and store keystore
      env:
        KEYSTORE_PATH: android/app/upload-keystore.jks
        KEYSTORE_JKS_BASE64: ${{ secrets.KEYSTORE_JKS_BASE64 }}
      run: |
        mkdir -p android/app
        echo "$KEYSTORE_JKS_BASE64" | base64 --decode > "$KEYSTORE_PATH"

    - name: Display stored keystore
      run: |
        ls -l android/app
